# Generated by Django 3.1 on 2021-02-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20210206_1214'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
                ('sales_return_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
            options={
                'verbose_name_plural': 'salesitem',
            },
        ),
    ]
