# Generated by Django 3.1 on 2021-02-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesreturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'verbose_name_plural': 'sales_return'},
        ),
    ]
