# Generated by Django 3.1 on 2021-02-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
