# Generated by Django 3.1 on 2021-02-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
